#!/bin/sh
# -------
# File:        auto-bridge
# Description: configure bridge automagically
# Author:      Luis Antonio Garcia Gisbert <luisgg@gmail.com> 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------

# vars
# ----
CONF_FILE="/etc/auto-bridge/auto-bridge.conf"
PREFIX="autobr-"

# funcs
# -----

die(){
	echo "$1" >&2
	exit 1
}

usage(){
	die "Usage: $(basename "$0") {add|del} PHYSICAL_DEVICE [MODE]"
}

add_bridge(){
	rc=0
	ip addr flush dev "$IFACE" || rc=$?
	[ $rc -ne 0 ] || brctl addbr "$BRIDGE" || rc=$?
	[ $rc -ne 0 ] || brctl addif "$BRIDGE" "$IFACE" || rc=$?
	[ $rc -ne 0 ] || ip link set dev "$BRIDGE" up || rc=$?
	[ $rc -ne 0 ] || dhclient "$BRIDGE" || rc=$?
	[ $rc -ne 0 ] || dhclient "$IFACE" || rc=$?
	return $rc
}

del_bridge(){
	rc=0
	ip addr flush dev "$BRIDGE" || rc=$?
	[ $rc -ne 0 ] || ip link set dev "$BRIDGE" down || rc=$?
	[ $rc -ne 0 ] || brctl deldbr "$BRIDGE" || rc=$?
	return $rc
}



[ $# -ge 2 ] || usage

ACTION="$1"
IFACE="$2"
MODE="$3"
[ "$MODE" ] $MODE="dhcp" 

[ -e  "/sys/class/net/$IFACE" ] || usage
[ ! -e "/sys/devices/virtual/net/$IFACE" ] || usage

BRIDGE="$PREFIX-${IFACE}"
	
rc=0
case "$ACTION" in
	add)
		add_bridge || rc=$?
		;;
	del)
		del_bridge || rc=$?
		;;
	*)
		usage
		;;
esac

exit $rc

