#!/bin/sh
# -------
# File:        auto-bridge
# Description: configure bridge automagically
# Author:      Luis Antonio Garcia Gisbert <luisgg@gmail.com> 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------

# vars
# ----
CONF_FILE="/etc/auto-bridge/auto-bridge.conf"


# funcs
# -----

die(){
	echo "$1" >&2
	exit 1
}

usage(){
	die "Usage: $(basename "$0") {add|del} PHYSICAL_DEVICE"
}


[ $# -eq 2 ] || usage
ACTION="$1"
IFACE="$2"
[ -e  "/sys/class/net/$IFACE2" ] && [ ! -e "/sys/devices/virtual/net/$IFACE" ] ; then
	
case "$ACTION" in
	add)
		
